-- Dropping if exists
drop table if exists confirmation_tokens CASCADE;
drop table if exists roles CASCADE;
drop table if exists users CASCADE;
drop table if exists users_roles CASCADE;

-- Creating confirmation token table
create table confirmation_tokens (
    token_id integer generated by default as identity,
    expire_date_time timestamp not null,
    rawtoken varchar(255) not null,
    user_id integer not null,
    primary key (token_id)
);

-- Creating roles table
create table roles (
    role_id integer generated by default as identity,
    name varchar(255),
    primary key (role_id)
);

-- Creating users table
create table users (
    user_id integer generated by default as identity,
    age integer not null check (age>=18),
    balance float not null check (balance>=0),
    driver_license varchar(255) not null,
    email varchar(255) not null,
    enabled boolean not null,
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    password varchar(255) not null,
    primary key (user_id)
);

-- Creating users <-> roles table
create table users_roles (
    user_id integer not null,
    role_id integer not null
);

-- Unique email constraint
alter table users
    add constraint email_unique unique (email);

-- Foreign key token -> user
alter table confirmation_tokens
    add constraint confirmation_tokens_fk_user_id
        foreign key (user_id)
            references users
            on delete cascade;

-- users_roles setup
alter table users_roles
    add constraint fk_role_id
        foreign key (role_id)
            references roles;
alter table users_roles
    add constraint users_roles_fk_user_id
        foreign key (user_id)
            references users;

-- Inserting admin role
insert into roles (name)
values
    ('ADMIN');

-- Inserting global admin user (email and password are fake)
insert into users (email, password, first_name, last_name, age, driver_license, enabled, balance)
values ('UserServiceGlobalAdmin@drivedynamics.com', '$2a$10$IQ/g9DnY1HGjtYiwJPPn5ubr8y.LY4yk3krvzxk/gecGSTJl25TRS', 'admin', 'global', 19, '', true, 0);

-- making admin user actual admin by adding record to users_records
insert into users_roles
values (1, 1);